// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgiijcqpcugxsmwytoem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnaWlqY3FwY3VneHNtd3l0b2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODczMjYsImV4cCI6MjA3MjU2MzMyNn0.z9uvDF-crcYAHACqXqdpVZAwtshXBtkOv18nEBlTXiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});